Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-16.10"
  config.vm.provision "shell",privileged: false, inline: "echo hello "
  config.vm.network "forwarded_port", guest: 8080, host: 8080
  config.vm.network "forwarded_port", guest: 4200, host: 4200  
  config.vm.network "forwarded_port", guest: 80, host: 8000
  config.vm.network "private_network", type: "dhcp"
 
  config.vm.provider "virtualbox" do |vb|
     vb.memory = 8124
     vb.cpus=4
   end
end


